version: "3"
services:
  db:
    container_name: mariaDB
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=seed0111
    ports:
      - 3306:3306
    volumes: 
      - /home/ubuntu/volumes/mysql:/var/lib/mysql
      - /home/ubuntu/volumes/conf.d:/var/lib/conf.d
    restart: always

#  insertDB:
#    container_name: insertDB
#    image: insertdata:1.0
#    depends_on:
#      - db

  master:
    container_name: master
    image: jenkinsci/jenkins:2.150.1-slim
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkinse_home
    depends_on:
      - db
